spring:
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driverClassName: org.h2.Driver
    username:
    password:


