spring:
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect





  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driverClassName: org.h2.Driver
    username:
    password:

  kafka:
     bootstrap-servers: localhost:9092
     consumer:
       group-id: products-consumer-grp
       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       value-deserializer : org.apache.kafka.common.serialization.StringDeserializer
server:
  port : 8082